CREATE TABLE [dbo].[DetArrangerStrategy] (
    [Key]                 INT           NOT NULL,
    [RunName]             NVARCHAR (64) NULL,
    [TerminateOnFirstFit] INT           NULL,
    [ArrangeGlobally]     INT           NULL,
    [ArrangeInCenter]     INT           NULL,
    [OwnerText]           NVARCHAR (15) NULL,
    [Number Of Items]     INT           NULL,
    [SearchArea1]         INT           NULL,
    [AreaPercent1]        INT           NULL,
    [MinDistance1]        FLOAT (53)    NULL,
    [MaxDistance1]        FLOAT (53)    NULL,
    [SearchArea2]         INT           NULL,
    [AreaPercent2]        INT           NULL,
    [MinDistance2]        FLOAT (53)    NULL,
    [MaxDistance2]        FLOAT (53)    NULL,
    [SearchArea3]         INT           NULL,
    [AreaPercent3]        INT           NULL,
    [MinDistance3]        FLOAT (53)    NULL,
    [MaxDistance3]        FLOAT (53)    NULL,
    [SearchArea4]         INT           NULL,
    [AreaPercent4]        INT           NULL,
    [MinDistance4]        FLOAT (53)    NULL,
    [MaxDistance4]        FLOAT (53)    NULL,
    [SearchArea5]         INT           NULL,
    [AreaPercent5]        INT           NULL,
    [MinDistance5]        FLOAT (53)    NULL,
    [MaxDistance5]        FLOAT (53)    NULL,
    [SearchArea6]         INT           NULL,
    [AreaPercent6]        INT           NULL,
    [MinDistance6]        FLOAT (53)    NULL,
    [MaxDistance6]        FLOAT (53)    NULL,
    [SearchArea7]         INT           NULL,
    [AreaPercent7]        INT           NULL,
    [MinDistance7]        FLOAT (53)    NULL,
    [MaxDistance7]        FLOAT (53)    NULL,
    [SearchArea8]         INT           NULL,
    [AreaPercent8]        INT           NULL,
    [MinDistance8]        FLOAT (53)    NULL,
    [MaxDistance8]        FLOAT (53)    NULL,
    [SearchArea9]         INT           NULL,
    [AreaPercent9]        INT           NULL,
    [MinDistance9]        FLOAT (53)    NULL,
    [MaxDistance9]        FLOAT (53)    NULL,
    [SearchArea10]        INT           NULL,
    [AreaPercent]         INT           NULL,
    [MinDistance10]       FLOAT (53)    NULL,
    [MaxDistance10]       FLOAT (53)    NULL,
    CONSTRAINT [PK_DetArrangerStrategy] PRIMARY KEY CLUSTERED ([Key] ASC),
    UNIQUE NONCLUSTERED ([Key] ASC)
);

