CREATE TABLE [dbo].[DetailProcessMain2CutScale] (
    [Key]             INT           NOT NULL,
    [RunName]         NVARCHAR (64) NULL,
    [OwnerText]       NVARCHAR (15) NULL,
    [Number of items] INT           NULL,
    [MainViewScale1]  FLOAT (53)    NULL,
    [Request1]        FLOAT (53)    NULL,
    [MainViewScale2]  FLOAT (53)    NULL,
    [Request2]        FLOAT (53)    NULL,
    [MainViewScale3]  FLOAT (53)    NULL,
    [Request3]        FLOAT (53)    NULL,
    [MainViewScale4]  FLOAT (53)    NULL,
    [Request4]        FLOAT (53)    NULL,
    [MainViewScale5]  FLOAT (53)    NULL,
    [Request5]        FLOAT (53)    NULL,
    [MainViewScale6]  FLOAT (53)    NULL,
    [Request6]        FLOAT (53)    NULL,
    [MainViewScale7]  FLOAT (53)    NULL,
    [Request7]        FLOAT (53)    NULL,
    [MainViewScale8]  FLOAT (53)    NULL,
    [Request8]        FLOAT (53)    NULL,
    [MainViewScale9]  FLOAT (53)    NULL,
    [Request9]        FLOAT (53)    NULL,
    [MainViewScale10] FLOAT (53)    NULL,
    [Request10]       FLOAT (53)    NULL,
    CONSTRAINT [PK_DetailProcessMain2CutScale] PRIMARY KEY CLUSTERED ([Key] ASC),
    UNIQUE NONCLUSTERED ([Key] ASC)
);

