CREATE TABLE [dbo].[DetailStyle] (
    [Key]                     INT            NOT NULL,
    [RunName]                 NVARCHAR (64)  NULL,
    [ViewArrangeStrategy]     INT            NULL,
    [DetailOrientation]       INT            NULL,
    [ObjectSelectionStrategy] INT            NULL,
    [TitleFormat]             NVARCHAR (MAX) NULL,
    [TitlePosition]           INT            NULL,
    [CutViewTitleFormat]      NVARCHAR (MAX) NULL,
    [CutViewTitlePosition]    INT            NULL,
    [ScaleFormat]             NVARCHAR (50)  NULL,
    [DateFormat]              NVARCHAR (50)  NULL,
    [FrameAppearance]         INT            NULL,
    [ObjectPosition]          INT            NULL,
    [AutomaticClipping]       INT            NULL,
    [OwnerText]               NVARCHAR (15)  NULL,
    [Number of items]         INT            NULL,
    [Request1]                INT            NULL,
    [Request2]                INT            NULL,
    [Request3]                INT            NULL,
    [Request4]                INT            NULL,
    [Request5]                INT            NULL,
    [Request6]                INT            NULL,
    [Request7]                INT            NULL,
    [Request8]                INT            NULL,
    [Request9]                INT            NULL,
    [Request10]               INT            NULL,
    CONSTRAINT [PK_DetailStyle] PRIMARY KEY CLUSTERED ([Key] ASC),
    UNIQUE NONCLUSTERED ([Key] ASC)
);

