CREATE TABLE [dbo].[DetViewDimRequestLinear] (
    [Key]                        INT            NOT NULL,
    [RunName]                    NVARCHAR (64)  NULL,
    [OwnerText]                  NVARCHAR (15)  NULL,
    [Direction]                  INT            NULL,
    [ArrangeGlobally]            BIT            NOT NULL,
    [ArrangeAbove]               BIT            NOT NULL,
    [GroupRelatedDimensions]     BIT            NOT NULL,
    [OneChainPerObjectInPoints1] BIT            NOT NULL,
    [AllowCombine]               BIT            NOT NULL,
    [AutomaticallySeparate]      BIT            NOT NULL,
    [Group]                      INT            NULL,
    [LabelPosition]              INT            NULL,
    [LabelContents]              NVARCHAR (MAX) NULL,
    [Number of Points]           INT            NULL,
    [Point1]                     INT            NULL,
    [Point2]                     INT            NULL,
    [Point3]                     INT            NULL,
    [Point4]                     INT            NULL,
    [Point5]                     INT            NULL,
    [Point6]                     INT            NULL,
    [Point7]                     INT            NULL,
    [Point8]                     INT            NULL,
    [Point9]                     INT            NULL,
    [Point10]                    INT            NULL,
    [Point11]                    INT            NULL,
    [Point12]                    INT            NULL,
    [Point13]                    INT            NULL,
    [Point14]                    INT            NULL,
    [Point15]                    INT            NULL,
    CONSTRAINT [PK_DetViewDimRequestLinear] PRIMARY KEY CLUSTERED ([Key] ASC),
    UNIQUE NONCLUSTERED ([Key] ASC)
);

